Introduce die function and colored output

diff --git a/pants b/pants
--- a/pants
+++ b/pants
@@ -31,13 +31,22 @@ SETUPTOOLS_REQUIREMENT="setuptools==5.4.1"
 VENV_PACKAGE=virtualenv-${VENV_VERSION}
 VENV_TARBALL=${VENV_PACKAGE}.tar.gz
 
-# The high-level flow:
-# 1.) Grab pants version from pants.ini or default to latest.
-# 2.) Check for a venv via a naming/path convention and execute if found.
-# 3.) Otherwise create venv and re-exec self.
-#
-# After that pants itself will handle making sure any requested plugins
-# are installed and up to date.
+COLOR_BLUE="\x1b[34m"
+COLOR_RED="\x1b[31m"
+COLOR_RESET="\x1b[0m"
+
+function log() {
+  echo -e "$@" 1>&2
+}
+
+function die() {
+  (($# > 0)) && log "${COLOR_RED}$*${COLOR_RESET}"
+  exit 1
+}
+
+function green() {
+  (($# > 0)) && log "${COLOR_GREEN}$*${COLOR_RESET}"
+}
 
 function tempdir {
   mktemp -d "$1"/pants.XXXXXX
@@ -51,11 +60,21 @@ function get_pants_ini_config_value {
   sed -ne "/${prefix}/ s#${prefix}##p" pants.ini
 }
 
+# The high-level flow:
+# 1.) Resolve the Python interpreter, defaulting to `python2.7`.
+# 2.) Grab pants version from pants.ini or default to latest.
+# 3.) Check for a venv via a naming/path convention and execute if found.
+# 4.) Otherwise create venv and re-exec self.
+#
+# After that pants itself will handle making sure any requested plugins
+# are installed and up to date.
+
 function determine_pants_runtime_python_version {
   python_bin_name="${PYTHON:-python2.7}"
-  if ! which "${python_bin_name}"; then
-    echo "Could not find ${python_bin_name}. Please ensure ${python_bin_name} is on your PATH." 1>&2
-    exit 1
+  if which "${python_bin_name}" >/dev/null; then
+    which "${python_bin_name}"
+  else
+    die "Could not find ${python_bin_name}. Please ensure ${python_bin_name} is on your PATH."
   fi
 }
 
